



name: Build CPClient

# Controls when the action will run. 
on:
  # Triggers the workflow on push for production branch
  push:
    branches: 
       - "**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build CPClient
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # macos-latest, ubuntu-latest, 

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Build
        run: npm start

      - name: Lint
        run: npm lint

      #- name: Make and Publish (Ubuntu)
      #  if: startsWith(matrix.os, 'ubuntu')
      #  run: yarn build-linux

      - name: Make and Publish (WINDOWS)
        if: startsWith(matrix.os, 'windows')
        run: npm build-win
        
      #- name: Make and Publish (MAC)
      #  if: startsWith(matrix.os, 'macos')
      #  run: yarn build-mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
            name: artifacts
            path: ./dist/
