name: Build-Windows

on:

  push:

    branches:

      - "**"

  workflow_call:

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install Node.js, NPM and Yarn

      uses: actions/setup-node@v4

    - name: Restore dependencies

      run: yarn install

    - name: Build Typescript

      run: yarn build-tsc

    - name: Build for Windows

      run: yarn build-win

    - name: Upload Artifacts

      uses: actions/upload-artifact@v4

      with:

        name: artifacts

        path: ./dist/

